#!/usr/bin/env python3
"""Generate a quality report for optimized Markdown docs.

This script is intentionally read-only for source documents. It validates the
output generated by reformat_md.py / optimize_md_deepseek.py so repeated DingTalk
regeneration has a stable quality gate and an actionable report.
"""
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path

_FRONTMATTER_RE = re.compile(r"\A---\n[\s\S]*?\n---\n?")
_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
_H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
_ESCAPE_RESIDUE_RE = re.compile(r"\\[+>\[\]()._-]|\\$")
_IMG_PREFIX_RE = re.compile(r"(.+?)_img_\d+_")


@dataclass
class FileIssue:
    path: str
    issues: list[str] = field(default_factory=list)


def _clean_title(value: str) -> str:
    value = value.replace("\\", "")
    value = value.replace("操作说明书", "").replace("操作说明", "")
    value = re.sub(r"[_\-（）()？?、，,\s]+", "", value)
    return value.strip()


def _has_frontmatter(text: str) -> bool:
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return False
    block = match.group(0)
    return "\ntitle:" in block and "\ndescription:" in block


def _strip_frontmatter(text: str) -> str:
    match = _FRONTMATTER_RE.match(text)
    return text[match.end():] if match else text


def _image_issue_messages(md_file: Path, text: str) -> list[str]:
    messages: list[str] = []
    for alt, raw_path in _IMAGE_RE.findall(text):
        path = raw_path.split("#", 1)[0].split("?", 1)[0]
        if re.match(r"^[a-z]+://", path) or path.startswith("/"):
            continue
        if not alt.strip() or alt.strip().lower() in {"image", "image.png", "图片", "截图"}:
            messages.append(f"图片 alt 过泛：{raw_path}")
        target = (md_file.parent / path).resolve()
        if not target.exists():
            messages.append(f"图片不存在：{raw_path}")
            continue
        prefix_match = _IMG_PREFIX_RE.match(target.name)
        if prefix_match:
            image_doc_prefix = _clean_title(prefix_match.group(1))
            doc_title = _clean_title(md_file.stem)
            if image_doc_prefix and doc_title and image_doc_prefix not in doc_title and doc_title not in image_doc_prefix:
                messages.append(f"图片名前缀疑似来自其他文档：{target.name}")
    return messages


def analyze_file(md_file: Path, root: Path) -> FileIssue | None:
    text = md_file.read_text(encoding="utf-8", errors="ignore")
    body = _strip_frontmatter(text)
    rel = str(md_file.relative_to(root))
    issue = FileIssue(path=rel)

    if not _has_frontmatter(text):
        issue.issues.append("缺少 title/description frontmatter")

    h1 = _H1_RE.findall(body)
    if not h1:
        issue.issues.append("缺少一级标题 H1")
    elif len(h1) > 1:
        issue.issues.append(f"存在多个 H1：{len(h1)} 个")

    if h1 and md_file.name != "index.md":
        expected = _clean_title(md_file.stem)
        actual = _clean_title(h1[0])
        if expected and actual and expected not in actual and actual not in expected:
            issue.issues.append(f"H1 与文件名不一致：{h1[0]}")

    line_count = len([ln for ln in body.splitlines() if ln.strip()])
    h2_count = len(re.findall(r"^##\s+", body, re.MULTILINE))
    if md_file.name != "index.md" and line_count < 8 and h2_count < 2:
        issue.issues.append(f"正文偏短：{line_count} 行有效内容")

    if _ESCAPE_RESIDUE_RE.search(body):
        issue.issues.append("仍存在疑似 Markdown 转义残留")

    issue.issues.extend(_image_issue_messages(md_file, text))

    return issue if issue.issues else None


def analyze_docs(root: Path) -> list[FileIssue]:
    issues: list[FileIssue] = []
    for md_file in sorted(root.rglob("*.md")):
        if any(part in {".vitepress", "node_modules"} for part in md_file.parts):
            continue
        found = analyze_file(md_file, root)
        if found:
            issues.append(found)
    return issues


def render_report(root: Path, issues: list[FileIssue]) -> str:
    total = len(list(root.rglob("*.md")))
    problem_count = len(issues)
    issue_count = sum(len(item.issues) for item in issues)
    lines = [
        "# 文档质量检查报告",
        "",
        "该报告由生成流程自动产生，用于检查从钉钉重新拉取并优化后的 Markdown 质量。",
        "",
        "## 汇总",
        "",
        f"- Markdown 文件数：{total}",
        f"- 存在问题的文件数：{problem_count}",
        f"- 问题总数：{issue_count}",
        "",
    ]
    if not issues:
        lines.extend(["## 结果", "", "未发现明显质量问题。", ""])
        return "\n".join(lines)

    lines.append("## 问题明细")
    lines.append("")
    for item in issues:
        lines.append(f"### `{item.path}`")
        lines.append("")
        for msg in item.issues:
            lines.append(f"- {msg}")
        lines.append("")
    return "\n".join(lines)


def write_report(root: Path, output: Path) -> tuple[int, int]:
    issues = analyze_docs(root)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_report(root, issues), encoding="utf-8")
    return len(issues), sum(len(item.issues) for item in issues)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Markdown quality report")
    parser.add_argument("root", help="Markdown root directory to inspect")
    parser.add_argument("-o", "--output", default="docs/doc-quality-report.md")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = Path(args.output).resolve()
    files, issues = write_report(root, output)
    print(f"Quality report: {output} ({files} files with issues, {issues} issues)")


if __name__ == "__main__":
    main()
